{% set name = "types-hdbcli" %}
{% set version = "2.21.0.20240621" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-hdbcli-{{ version }}.tar.gz
  sha256: c696aea7609319e79d94f2e6cd7216e327f1bc88309ecee7737d82c846a0b836

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/hdbcli-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\hdbcli-stubs\\__init__.pyi exit 1  # [win]

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for hdbcli
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxvolk
